enyo.depends(
	"$lib/layout",
	"$lib/onyx",
	"datasource/LocalStorage.js",
	"datasource/HttpCsvReader.js",
	"datasource/NutritionData.js",
	"NutritionalSheet.css",
	"NutritionalSheet.js",
	"NutrimentList.js",
	"FoodResultList.js",
	"FoodResultList.css",
	"FavoriteList.js",
	"FavoriteList.css",
	"l10n.js",
	"App.css",
	"App.js",
	"logo.css"
);
